repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # renovate: depName=pre-commit/pre-commit-hooks
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
        exclude: lazy-lock.json
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1 # renovate: depName=pre-commit/mirrors-prettier
    hooks:
      - id: prettier
        name: prettier yaml
        types: [yaml]
