name: chezmoi init
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  getModules:
    name: chezmoi init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run chezmoi init in arch linux docker container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/scottames/archlinux-toolbox:latest # https://github.com/scottames/boxes
          options: -v ${{ github.workspace }}:/home/container/src/scottames/dots
          run: /home/container/src/scottames/dots/scripts/init.sh --no-tty
