on:
  push:
    branches:
      - main
    paths:
      - pkg/**
      - magefiles/**
      - CHANGELOG.md
      - go.*
permissions:
  contents: write
  pull-requests: write
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: dots
